# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05c5cb5a888266137b2301863fcc37d44637724ac5110cbf2768a3489e5113fa8f29a69cfb9afbf0f94e2ce1009664175b5b13b5738b59ead8bb6d90a876ff6d

test:
  secret_key_base: 741328ffedd59d6d082576abbb8f846d6433e60c02b3eb604bb60f1dd20a776fb081a4e2b7518c5e50765581cffee8ab204240536af76523f32d684bbbcb32a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
